---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: say-hi
  labels:
    app: say-hi
    name: {{ required "A valid .Values.name entry required!" .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: say-hi
      name: {{ required "A valid .Values.name entry required!" .Values.name }}
  template:
    metadata:
      labels:
        app: say-hi
        name: {{ required "A valid .Values.name entry required!" .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: say-hi
        env:
        - name: NAME
          value: {{ required "A valid .Values.name entry required!" .Values.name }}
        ports:
        - containerPort: 5000